// Definitions must behave exactly as in 1.0.1. The expected output in
// fixtures/definitions-golden.json was generated by the released 1.0.1 code.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { beforeEach, describe, it } from 'node:test';
import { noteBaseName } from '../src/core/notes';
import { renderTemplate } from '../src/core/render';
import { lookupWord } from '../src/lookups/definitions/sources';
import { buildVariables, DEFAULT_TEMPLATE } from '../src/lookups/definitions/template';
import type { WordEntry } from '../src/lookups/definitions/types';
import { fake, resetNetwork } from './support/network';

interface Golden {
	builtInTemplate: string;
	entries: Record<string, WordEntry>;
	cases: { name: string; entry: string; sense: number; template: string | null; expected: string }[];
	names: { input: string; expected: string }[];
}
const golden = JSON.parse(readFileSync('tests/fixtures/definitions-golden.json', 'utf8')) as Golden;
const now = { format: (format: string) => `<${format}>` };

describe('definitions match 1.0.1', () => {
	it('the built-in template is unchanged', () => {
		assert.equal(DEFAULT_TEMPLATE, golden.builtInTemplate);
	});

	for (const c of golden.cases) {
		it(`renders the same note: ${c.name}`, () => {
			const entry = golden.entries[c.entry];
			assert.ok(entry);
			const sense = entry.senses[c.sense];
			assert.ok(sense);
			const actual = renderTemplate(c.template ?? DEFAULT_TEMPLATE, buildVariables(entry, sense), now);
			assert.equal(actual, c.expected);
		});
	}

	it('names notes the same way', () => {
		for (const { input, expected } of golden.names) assert.equal(noteBaseName(input), expected, input);
	});
});

describe('definition lookups', () => {
	beforeEach(resetNetwork);
	const options = { language: 'en', apiKey: '' };

	it('looks up a word in Free Dictionary API', async () => {
		const { entry, fallback } = await lookupWord('run', 'free-dictionary', options, true);
		assert.equal(entry.word, 'run');
		assert.ok(entry.senses.length > 5);
		assert.equal(fallback, undefined);
	});

	it('falls back to Wiktionary when Free Dictionary API is down', async () => {
		fake('freedictionaryapi.com', { status: 503, text: '', headers: {} });
		const { entry, fallback } = await lookupWord('run', 'free-dictionary', options, true);
		assert.equal(entry.source.name, 'Wiktionary');
		assert.equal(fallback?.error.kind, 'server');
	});

	it('reports a word that does not exist', async () => {
		await assert.rejects(lookupWord('zzqxvbn', 'free-dictionary', options, true), {
			kind: 'not-found',
			message: 'No definitions found for "zzqxvbn".',
		});
	});
});
